name: unit tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  rust:
    name: rust
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup rust
        uses: ./.github/actions/setup-rust

      - name: run tests
        run: make rust-test

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup rust
        uses: ./.github/actions/setup-rust

      - name: run clippy
        run: make clippy
